# Generated by Django 3.0 on 2020-03-31 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mdl_participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('topic', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='mdl_rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('topic', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='mdl_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.CharField(choices=[('apartement', 'apartement'), ('land', 'land'), ('home', 'home')], default='apartement', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='mdl_land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('topic', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamahang.mdl_sale')),
            ],
        ),
        migrations.CreateModel(
            name='mdl_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('topic', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamahang.mdl_sale')),
            ],
        ),
        migrations.CreateModel(
            name='mdl_apartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('topic', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('apartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamahang.mdl_sale')),
            ],
        ),
    ]
