# Generated by Django 3.0 on 2020-04-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamahang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdl_rent',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
