# Generated by Django 3.0 on 2020-04-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamahang', '0002_auto_20200401_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdl_rent',
            name='img',
            field=models.FilePathField(path='/images'),
        ),
    ]
