# Generated by Django 3.0 on 2020-04-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamahang', '0004_mdl_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdl_contact',
            name='mobile',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
